#!/bin/bash

#systemd-inhibit --what=sleep --why="Backup running" bash -c 

# Paths
SOURCE="/mnt/MergedStorage"
DEST="/mnt/backup"
MAX_BACKUPS=10

DATE=$(date +"%Y%m%d")
BACKUP_FILE="${DEST}/fileserver_backup_${DATE}.tar.gz"

sudo tar -czf "$BACKUP_FILE" -C "$SOURCE" .

BACKUP_COUNT=$(ls -1 ${DEST}/fileserver_backup_*.tar.gz 2>/dev/null | wc -l)

if [ "$BACKUP_COUNT" -gt "$MAX_BACKUPS" ]; then
  OLDEST=$(ls -1t ${DEST}/fileserver_backup_*.tar.gz | tail -1)
  sudo rm -f "$OLDEST"
fi
